"use client";

import { FormEvent, useMemo, useState } from "react";

type Evidence = { source_id: string; excerpt: string; relation: string };
type TestCase = { id:string; title:string; kind:"positive"|"negative"|"boundary"; priority:string; preconditions:string[]; steps:{action:string;expected:string}[]; evidence:Evidence[] };
type Run = { run_id:string; confidence:number; test_cases:TestCase[]; warnings:string[] };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export default function Home() {
  const [requirement,setRequirement]=useState("Customer must receive an email receipt after a successful payment.");
  const [sourceId,setSourceId]=useState("JIRA-428");
  const [run,setRun]=useState<Run|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const counts=useMemo(()=>!run?{total:0,evidence:0}:{total:run.test_cases.length,evidence:run.test_cases.filter(t=>t.evidence.length>0).length},[run]);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch(`${API}/api/v1/agents/test-case-generator/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requirement,source_id:sourceId||null})});if(!response.ok)throw new Error(`API returned ${response.status}`);setRun(await response.json())}catch(err){setError(err instanceof Error?err.message:"Unable to run agent")}finally{setLoading(false)}}
  return <main className="shell"><aside className="rail"><div className="brand"><span>Q</span><strong>Agentic QA</strong></div><nav><button className="active">Overview</button><button>Build</button><button>Test</button><button>Analyze</button><button>Release</button><button>Learn</button></nav><div className="railFooter">Local workspace<br/><small>v0.1.0</small></div></aside><section className="workspace"><header><div><p className="eyebrow">QUALITY CONTROL PLANE</p><h1>Test design, with evidence.</h1></div><div className="status"><i/> API-ready vertical slice</div></header><div className="metrics"><article><span>Executable agents</span><strong>1</strong><small>3 more in registry</small></article><article><span>Generated tests</span><strong>{counts.total}</strong><small>this run</small></article><article><span>Evidence coverage</span><strong>{counts.total?`${Math.round((counts.evidence/counts.total)*100)}%`:"—"}</strong><small>no silent claims</small></article><article><span>Confidence</span><strong>{run?`${Math.round(run.confidence*100)}%`:"—"}</strong><small>source-aware</small></article></div><div className="grid"><form className="panel composer" onSubmit={submit}><div className="panelTitle"><div><span>AGENT 01</span><h2>Test Case Generator</h2></div><b>READY</b></div><label>Requirement<textarea value={requirement} onChange={e=>setRequirement(e.target.value)}/></label><label>Evidence source<input value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder="JIRA-428"/></label><button className="run" disabled={loading||requirement.trim().length<5}>{loading?"Running…":"Run agent →"}</button>{error&&<p className="error">{error}</p>}<p className="note">Deterministic local engine is enabled; no LLM key is required for this slice.</p></form><section className="panel output"><div className="panelTitle"><div><span>OUTPUT</span><h2>Evidence-linked cases</h2></div>{run&&<b>{run.test_cases.length} CASES</b>}</div>{!run&&<div className="empty"><strong>Nothing generated yet</strong><p>Run the test-design agent. Each case will carry the requirement fragment that justified it.</p></div>}{run?.test_cases.map(test=><article className="test" key={test.id}><div className="testHead"><div><code>{test.id}</code><h3>{test.title}</h3></div><span className={`pill ${test.kind}`}>{test.kind}</span></div><ol>{test.steps.map((step,index)=><li key={index}><b>{step.action}</b><span>{step.expected}</span></li>)}</ol><div className="evidence"><span>EVIDENCE</span><code>{test.evidence[0].source_id}</code><p>“{test.evidence[0].excerpt}”</p></div></article>)}</section></div></section></main>;
}
